# Redocly configuration for OpenAPI 3.2
# Schemas use OpenAPI 3.1+ style: type arrays for nullable (e.g., type: [string, "null"])

apis:
  main:
    root: openapi.yaml

rules:
  # Disable struct rule that flags `nullable` (3.0 -> 3.1 migration)
  struct: off

  # Keep other validation rules
  info-license-strict: warn
  no-server-example.com: warn
  operation-4xx-response: warn
  no-unused-components: warn
